default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coffeebean_development
  user: vboxuser
  password: vboxuser
  pool: 5
  host: localhost

test:
  <<: *default
  database: coffeebean_test
  user: vboxuser
  password: vboxuser

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
